package es.npatarino.android.gotchallenge.common

class CharactersName {
    companion object {
        const val CHARACTER_OLLY = "Olly"
        const val CHARACTER_ALISSER = "Alliser Thorne"
        const val CHARACTER_BERIC = "Beric Dondarrion"
        const val CHARACTER_XARO = "Xaro Xhoan Daxos"
        const val CHARACTER_LORAS = "Loras Tyrell"
        const val CHARACTER_GREY = "Grey Worm"
        const val CHARACTER_OBARA = "Obara Sand"
        const val CHARACTER_DORAN = "Doran Martell"
        const val CHARACTER_GREGOR = "Gregor Clegane"
        const val CHARACTER_LANCEL = "Lancel Lannister"
        const val CHARACTER_YARA = "Yara Greyjoy"
        const val CHARACTER_WALDER = "Walder Frey"
        const val CHARACTER_RENLY = "Renly Baratheon"
        const val CHARACTER_MYRCELLA = "Myrcella Baratheon"
        const val CHARACTER_LYSA = "Lysa Arryn"
        const val CHARACTER_ROBIN = "Robin Arryn"
        const val CHARACTER_BROHN = "Bronn"
        const val CHARACTER_CERSEI = "Cersei Lannister"
        const val CHARACTER_OBERYN = "Oberyn Martell"
        const val CHARACTER_HODOR = "Hodor"
        const val CHARACTER_LORD = "Lord Varys"
        const val CHARACTER_JORAH = "Jorah Mormont"
        const val CHARACTER_MARGAERY = "Margaery Tyrell"
        const val CHARACTER_SANSA = "Sansa Stark"
        const val CHARACTER_PETYR = "Petyr Baelish"
        const val CHARACTER_EDDARD = "Eddard Stark"
        const val CHARACTER_KHAL = "Khal Drogo"
        const val CHARACTER_THEON = "Theon Greyjoy"
        const val CHARACTER_STANNIS = "Stannis Baratheon"
        const val CHARACTER_JON = "Jon Snow"
        const val CHARACTER_JAIME = "Jaime Lannister"
        const val CHARACTER_ARYA = "Arya Stark"
        const val CHARACTER_DAENERYS = "Daenerys Targaryen"
        const val CHARACTER_TYRION = "Tyrion Lannister"
    }
}